# Copyright (c) 2026, Nepher Robotics
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Shared MDP terms for G1 run / jump / course environments."""

from .actions import JointPdAction, JointPdActionCfg, TrackerAction, TrackerActionCfg
from .commands import JumpCommand, JumpCommandCfg
from .curriculums import jump_cmd_levels, lin_vel_cmd_levels
from .events import reset_from_runin_bank, reset_root_and_joints
from .jump_envelope import (
    APEX_ASYM_MIN,
    ARM_SPAN_APEX,
    D_OBSTACLE_MAX,
    D_OBSTACLE_MIN,
    ELBOW_FLIGHT,
    FLIGHT_DIST_MAX,
    FLIGHT_DIST_MIN,
    FOOT_SEP_HARD,
    FOOT_SEP_MAX_APEX,
    FOOT_SEP_MAX_FLIGHT,
    FOOT_SEP_SOFT,
    H_MAX,
    H_MIN,
    HAND_RISE_APEX,
    RISE_HARD_EXTRA,
    TUCK_EXTENDED,
    apex_rise_target,
    clamp_flight_distance,
    flight_cap,
    foot_sep_flight_max,
    foot_sep_hard,
    foot_sep_soft,
    map_takeoff_targets,
    pitch_apex_target,
    pitch_takeoff_target,
    push_fold_target,
    swing_ext_target,
    takeoff_standoff,
    tuck_apex_target,
)
from .observations import (
    amp_obs_single,
    base_height,
    base_lin_vel,
    base_lin_vel_z,
    foot_air_time,
    foot_contacts,
    generated_commands,
    jump_commands,
    last_action,
    reduced_coords_proprio,
    velocity_commands,
)
from .rewards import (
    action_rate_l2,
    alive_bonus,
    flat_orientation,
    flight_distance_progress,
    foot_clearance,
    heading_keep,
    land_absorb,
    land_and_idle,
    lin_vel_z_l2,
    obstacle_clearance,
    success_clear,
    success_land_stable,
    takeoff_launch,
    track_ang_vel_z_exp,
    track_lin_vel_xy_exp,
)
from .terminations import (
    bad_orientation,
    balloon_height,
    bounce_walk,
    extreme_foot_split,
    heading_blowout,
    illegal_contact,
    illegal_takeoff,
    jump_success,
    no_liftoff_timeout,
    post_land_timeout,
    prep_timeout,
    root_height_below,
    update_jump_state,
)

__all__ = [
    "JointPdAction",
    "JointPdActionCfg",
    "TrackerAction",
    "TrackerActionCfg",
    "JumpCommand",
    "JumpCommandCfg",
    "jump_cmd_levels",
    "lin_vel_cmd_levels",
    "reset_from_runin_bank",
    "reset_root_and_joints",
    "APEX_ASYM_MIN",
    "ARM_SPAN_APEX",
    "D_OBSTACLE_MAX",
    "D_OBSTACLE_MIN",
    "ELBOW_FLIGHT",
    "FLIGHT_DIST_MAX",
    "FLIGHT_DIST_MIN",
    "FOOT_SEP_HARD",
    "FOOT_SEP_MAX_APEX",
    "FOOT_SEP_MAX_FLIGHT",
    "FOOT_SEP_SOFT",
    "H_MAX",
    "H_MIN",
    "HAND_RISE_APEX",
    "RISE_HARD_EXTRA",
    "TUCK_EXTENDED",
    "apex_rise_target",
    "clamp_flight_distance",
    "flight_cap",
    "foot_sep_flight_max",
    "foot_sep_hard",
    "foot_sep_soft",
    "map_takeoff_targets",
    "pitch_apex_target",
    "pitch_takeoff_target",
    "push_fold_target",
    "swing_ext_target",
    "takeoff_standoff",
    "tuck_apex_target",
    "amp_obs_single",
    "base_height",
    "base_lin_vel",
    "base_lin_vel_z",
    "foot_air_time",
    "foot_contacts",
    "generated_commands",
    "jump_commands",
    "last_action",
    "reduced_coords_proprio",
    "velocity_commands",
    "action_rate_l2",
    "alive_bonus",
    "flat_orientation",
    "flight_distance_progress",
    "foot_clearance",
    "heading_keep",
    "land_absorb",
    "land_and_idle",
    "lin_vel_z_l2",
    "obstacle_clearance",
    "success_clear",
    "success_land_stable",
    "takeoff_launch",
    "track_ang_vel_z_exp",
    "track_lin_vel_xy_exp",
    "bad_orientation",
    "balloon_height",
    "bounce_walk",
    "extreme_foot_split",
    "heading_blowout",
    "illegal_contact",
    "illegal_takeoff",
    "jump_success",
    "no_liftoff_timeout",
    "post_land_timeout",
    "prep_timeout",
    "root_height_below",
    "update_jump_state",
]
